services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Rms\RmsExtlocateExtend\:
        resource: "../Classes/*"

    Rms\RmsExtlocateExtend\Command\CleanuIpCacheCommand:
        tags:
            - name: "console.command"
              command: "rms_extlocate:cleanup_ip_cache"
              description: "Cleanup IP geolocation cache"
